### ISSUE TITLE
2014-07-09CSW 在比特币墨尔本大会上接受采访视频已失效

### ISSUE THREAD

**Issue by bitmaner** [Time02/SatoshiTimeLine#3]
打开链接提示：
“视频无法播放
由于Dale Dickins提出了版权主张，此视频已无法播放。”
建议更新为：
https://www.youtube.com/watch?v=gYskRI0ynAM
https://www.youtube.com/watch?v=HwopmmsNeCs
https://www.youtube.com/watch?v=N1yNQSW8jGA

**Comment by Time02** [comment]
谢谢，已经修复。
