### ISSUE TITLE
CSW在Northumbria University法律硕士毕业论文

### ISSUE THREAD

**Issue by bitseaman** [Time02/SatoshiTimeLine#4]
链接：https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2953929
论文日期，2008-4-17，早于比特币白皮书发布日期。在论文26页，CSW提到新型的数字现金（digital cash）的发行，并在21条注释中说明P2P在此指的是person2person。

**Comment by Time02** [comment]
我仔细看了下26页，确实是比特币雏形。稍后更新
